version: '3.8'

services:
  web:
    build: ./web  # Construye la imagen usando el Dockerfile en la carpeta 'web'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      # Agrega otras variables de entorno
    restart: always

  redis:
    image: "redis:alpine"